---
title: "基于Vine-Copula模型的我国金融市场内部风险传染效应研究"
author: "曾远征"
date: "2019-03"
output:
  bookdown::html_document2:
    number_sections: true
    seq_numbering: true
    fig_caption: true
    highlight: haddock
    theme: null
    md_extensions: +east_asian_line_breaks
    keep_md: true
    toc: false
    pandoc_args: ["--filter", "pandoc-crossref", "-M", "eqnPrefix="]
  bookdown::word_document2:
    fig_caption: true
    reference_docx: ./style/word-styles-02.docx
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--filter", "pandoc-crossref"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    latex_engine: xelatex
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--listing", "--filter", "pandoc-crossref"]
css: ./style/markdown.css
autoEqnLabels: true
eqnPrefixTemplate: ($$i$$)
linkReferences: true
bibliography: Bibfile.bib
csl: ./style/chinese-gb7714-2005-numeric.csl
link-citations: true
---

**TODO**



```{r setup, echo=F}
knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(echo = FALSE, results = 'hide')
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
```

```{r prepare}
rm(list=ls())
options(digits=4)
options(scipen=100)
graphics.off()
Sys.setlocale("LC_ALL", "Chinese")
```


# 简介
文章主体结构：
我国金融市场分为货币市场、资本市场、外汇市场、黄金市场，因此选用的标的资产分别为：

* 货币市场：三月期国债收益率；
* 资本市场
 + 证券市场：上证综指（沪深300指数）
 + 期货市场：沪深300期货指数
* 外汇市场：人民币兑美元汇率（间接标价法）
* 黄金市场：上海交易所黄金现货-AU100

研究证券市场内部之间的风险传染

* 分为上证综指、深证成指、创业板指，研究三个市场内部的风险传染
[@bedford2001]
# 参考文献
[//]: # (\bibliography{Bibfile})
